site_name: Shift Software

theme:
  
  icon:
    admonition:
    <type>: <icon> 
    
  name: material
  
  palette:
    primary: amber

  features:
    - navigation.tabs
 
  favicon: images/favicon.png # unfinished


  logo: assets/shift logo.png



markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

