site_name: Shift Software

theme:
  
  icon:
    admonition:
    <type>: <icon> 
    
  name: material
  
  palette:
    primary: amber

  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.sections 



 
  favicon: images/favicon.png # unfinished


  logo: assets/shift logo.png



markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Home: index.md  
  - About : 
            - about/strategy-and-vision.md
            - about/code-of-conduct.md
            - about/Developers.md
  - Philosophy : 
            - Philosophy/philosophy.md
            - Philosophy/characteristics.md
  - Software Development : 
            - software-development/tasks.md
            - software-development/continuous-integration.md
            - software-development/automated-testing.md
            - software-development/continuous-delivery.md
